# In the experiment data directory, make a new folder called DE_analysis and add the files:
# 1) SRA experiment metadata file detailing the condition of each run
# 2) tx2gene file

# 1st command line argument: metadata file listing the condition of each SRA run (e.g. M vs BS). An example is in this directory.
# 2nd command line argument: tx2gene file generated by running make_tx2gene_file.py
# 3rd command line argument: the directory where the salmon quant.sf files are. Note the prefix of these files should match the run names in metadate file
# 4th command line argument: the number of replicates for each condition
# 5th command line argument: the directory where DE_results files should be saved

args = commandArgs(trailingOnly = TRUE)

metadata_file <- args[1]
tx2gene_file <- args[2]
quant_sf_directory <- args[3]
replicate_number <- args[4]
results_directory <- args[5]

library(DESeq2)
library(tximport)
library(readr)

summary_statistics <- function(res, filter) {
  number_DE_genes <- sum(res$padj < alpha, na.rm = TRUE)
  print(sprintf("Number of DE expressed genes for %s is:", filter))
  print(number_DE_genes)
  print(sprintf("Summary for results using %s:", filter))
  print(summary(res))
}

samples <- read.table(metadata_file, header = TRUE)

tx2gene <- read_csv(tx2gene_file)  ## manually created dict of gene transcripts to locus

files <- file.path(quant_sf_directory, sprintf("%s_quant.sf", samples$Run))

stopifnot(all(file.exists(files)))

names(files) <- samples$Run

txi <- tximport(files, type = "salmon", tx2gene = tx2gene)

head(txi$counts)



sampleTable <- data.frame(condition = factor(rep(c("M", "BS"), each = replicate_number)))  # each is the number of replicates per condition

rownames(sampleTable) <- colnames(txi$counts)

dds <- DESeqDataSetFromTximport(txi, sampleTable, ~condition)

dds <- DESeq(dds)

## Results using DESeq2 Independent Filtering (based on optimisation of number of
## DE genes given a p value threshold (alpha))
alpha <- 0.05
res1 <- results(dds, alpha = alpha)
summary_statistics(res1, "DESeq2 filter")
write.csv(as.data.frame(res1), file = sprintf("%s/results.csv", results_directory))

## Results using predefined cutoff based on the mean of normalised counts
## (baseMean) of a gene
cutoff <- 2
dds_filtered <- dds[res1$baseMean > cutoff, ]
res2 <- results(dds_filtered, independentFiltering = FALSE)
summary_statistics(res2, "my baseMean cutoff")
write.csv(as.data.frame(res2), file = sprintf("%s/results_filtered_baseMean_%s.csv", results_directory, toString(cutoff)))
